# -*- coding: utf-8 -*-
"""Python_para_Análise_de_dados_Numpy_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eu6rMv62BHaWSPo31lXZZ857jpv93WdQ

<h2>Python para Análise de Dados - Numpy</h2>

Iremos aprender a trabalhar com a biblioteca Numpy.

<h3>Acessando Dimensões no Array</h3>
"""

# Importando o Numpy
import numpy as np

# Gera um array aleatório de 10 linhas e 2 colunas
# formato linha,coluna
my_array = np.random.random([10,2])

my_array

# Imprimindo o primerio elemento (1 linha)
my_array[0]

# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

# Primeiro elemento da coluna 1
my_array[0][1]

# Segundo elemento da coluna 1
my_array[1][1]

# Segundo elemento da coluna escrito com vírgula
# O primeiro valor especifica a linha e o segundo valor especifica a coluna
my_array[1,1]

# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

# Imprime todas as linhas da coluna 1 * 10
my_array[:,1] * 10

# Comparação retorna índices
my_array > 0.50

# Acessando valores por índices
my_array[my_array > 0.50]

"""<h3> Carregar Arrays Numpy a partir de arquivos de arquivos de texto</h3>"""

# Lendo um arquivo do tipo .txt
dataset = np.loadtxt('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/dataset_array.txt',delimiter=',')

dataset.shape

dataset

# Carregando um arquivo dividido em 3 arrays
a, b, c = np.loadtxt('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/dataset_valores.txt', skiprows = 1, unpack = True)

# Array a
a

# Array b
b

# Array c
c

# Carrega o arquivo ignorando as 2 primeiras linhas e preenchendo os valores vazios por 0-zero
# Obs: os valores string também são convertidos!!

dataset = np.genfromtxt('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/dataset_valores_vazio.txt', skip_header=2, filling_values=0)

# Imprimindo o dataset
dataset

