# -*- coding: utf-8 -*-
"""Estruturas Condicionais.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-b28ePvC_VrORBYdd2VaO2Nj_KWhbf65

<h2> Trabalhando com Estruturas Condicionais </h2>
"""

# Retorno booleano
10 > 1

# Retorno booleano
5 <= 4

# Se a instrução for verdadeira, executa as instruções seguintes
# Cuidado com identação!!
if 10 > 1:
  print ('Verdadeiro')
  print (1 + 2)
  print ('Último comando')

"""<h2> Instrução ELSE </h2>"""

# A instrução ELSE é executada caso a instrução IF for FALSA

# Instrução else
if 10 > 20:
  print ('Verdadeiro')
else:
  print ('Falso')

# Quando usamos o Operador Lógico OR basta UMA condição ser verdadeira para toda consição ser verdadeira

# Testando o Operador Lógico OR
Nome = 'Rodrigo'

if 10 > 100 or Nome == 'Rodrigo':
  print ('Olá Rodrigo, seja bem vindo!')
else:
  print ('Você não é Rodrigo.')

# Testando o operador AND. (As duas condições devem ser verdadeiras.)
if 10 > 100 and Nome == 'Rodrigo':
  print ('Olá Rodrigo, seja bem vindo!')
else:
  print ('Você não é o Rodrigo.')

"""<h2> Entendendo a Consição ELIF </h2>"""

# A Instrução ELIF é acionada caso a instrução IF for falsa!
# A instrução ELIF é uma instrução do tipo -> SENÃO SE
valor = 200

# Entendendo a instrução ELIF
if valor > 100:
  print ('Ok, Valor é maior que 100!')
elif valor > 50:
  print ('Ok, Valor é maior que 50 e menor que 100!')
else:
  print('Operação inválida, valores devem ser maiores que 50!')

"""<h2> Instruções IF aninhadas</h2>"""

usuario = 'Rodrigo'
senha = 'data_science'

if usuario == 'Rodrigo':
  if senha == 'data_science':
    print ('Ok, tudo certo!')
  else:
    print ('Nome de usuário correto, você esqueceu a senha?')
else:
  print ('Nome de Usuário Inválido!!')