# -*- coding: utf-8 -*-
"""Manipulando Arquivos no Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1chtiGFiCDIiRuWqsVRL_qExwk-oZkcSY

<h2>Manipulando Arquivos no Python</h2>
"""

#Função nativa open() gera um objeto do tipo arquivo
# Base de dads gratuita 'automobile' https://archive.ics.uci.edu/ml/datasets/Automobile
# Download no Github (https://github.com/minerandodados/mdrepo/blob/master/automobile.csv)
file = open('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/automobile.csv', 'r')

# Métodos disponíveis
print (file)

# Modos de abertura de arquivos
# r - Modo padrão de abertura. Permite apenas leitura do arquivo.
# w - Modo de escrita. Permite escrita no arquivo.
# a - Modo de escrita do tipo acrescentar. Permite acrescentar informação no final do arquivo.

# Lendo várias linha do arquivo.
lista = file.readlines()
print (type(lista))

for i in lista:
  print (i)

# Imprime a quantidade de caracteres que contém no arquivo
print (file.tell())

# Lendo um arquivo
file = open('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/automobile.csv')
print (file.read())

"""<h2>Interando sobre um arquivo</h2>"""

type (file)

# Loops para interação no arquivo ajuda no uso de memória em arquivos grandes
file = open('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/automobile.csv','r')
for linha in file:
  print (linha)

"""<h2>Escrevendo em Arquivos</h2>"""

# Abre o arquivo em modo de escrita
file2 = open ('resultados.txt','w')

# Usando método write() para escrever no arquivo
file2.write('Data Science é a profissão do futuro!')
file2.write('Minerando Dados a sua comunidade de Data Science.')

# Fecha o arquivo com o método close()
file2.close()

# Tentando ler o arquivo // Não sendo possível pois precisa ser aberto novamente no modo leitura
file2.read()

# Abrir o arquivo em modo de leitura
file2 = open('resultados.txt','r')

# Ler linha a linha
file2.readlines()

# Use o modo de abertura 'a' para adicionar linhas no final do arquivo
file2 = open('resultados.txt','a')

file2.write('Última linha do arquivo!')
file2.close()

file2 = open('resultados.txt','r')
file2.readlines()

"""<h2>Método writelines()</h2>"""

# O método writelines() permite escrever uma lista de dados no arquivo
lista = ['Manipular arquivos no Python é fácil', 'Segunda Linha!', 'Mais uma linha!']

# Abre o arquivo para escrita (sobrescreve!!)
file2 = open('resultados.txt','w')

# Escreve a lista de strings
file2.writelines(lista)
file2.close()

# Abre para leitura e imprime no formato de lista
file2 = open('resultados.txt','r')
file2.readlines()

"""<h2>Trabalhando com a instrução 'whith'</h2>"""

# Com a instrução with você não precisa fechar o arquivo explicitamente
# O Python já fecha o arquivo quando os blocos não estão sendo utilizados
with open('resultados.txt') as file2:
  print(file2.read())

# O arquivo já foi fechado pelo Python!
# Aparece um erro informado que o arquivo foi fechado
file2.read()

# Cria uma lista com as linhas do arquivo e fecha após concluir
with open('/content/drive/My Drive/Colab Notebooks/ Data Science - Minerando Dados/datasets/automobile.csv') as file2:
  data = file2.readlines()

# Arquivo já fechado!
# Um erro aparece informando
file2.read()

# Imprime a lista
# Sendo necessário só chamar o objeto data em que recebeu o arquivo
data

"""<h2> Separando Palavras por Linhas</h2>"""

for linha in data:
  print (linha.split())

